// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1xJuMx9a8AX1ztxFt1jkfnSUNT-JukcM',
    appId: '1:602287237067:web:6d7ea9dcf3604becf4384e',
    messagingSenderId: '602287237067',
    projectId: 'cipher-affair-69d2d',
    authDomain: 'cipher-affair-69d2d.firebaseapp.com',
    storageBucket: 'cipher-affair-69d2d.appspot.com',
    measurementId: 'G-Q7MQYD8QV2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuuvhNLXKbUXwN-3_aECkA1l4FTIgFKk8',
    appId: '1:602287237067:android:64f2148fbfab9ebff4384e',
    messagingSenderId: '602287237067',
    projectId: 'cipher-affair-69d2d',
    storageBucket: 'cipher-affair-69d2d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsRzGUG7lML2fwUuiKg7dtG66W-HUcKiU',
    appId: '1:602287237067:ios:82b1428813c9e4c1f4384e',
    messagingSenderId: '602287237067',
    projectId: 'cipher-affair-69d2d',
    storageBucket: 'cipher-affair-69d2d.appspot.com',
    iosBundleId: 'com.example.cipherAffair',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsRzGUG7lML2fwUuiKg7dtG66W-HUcKiU',
    appId: '1:602287237067:ios:82b1428813c9e4c1f4384e',
    messagingSenderId: '602287237067',
    projectId: 'cipher-affair-69d2d',
    storageBucket: 'cipher-affair-69d2d.appspot.com',
    iosBundleId: 'com.example.cipherAffair',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1xJuMx9a8AX1ztxFt1jkfnSUNT-JukcM',
    appId: '1:602287237067:web:7f5ae82d080e8ddcf4384e',
    messagingSenderId: '602287237067',
    projectId: 'cipher-affair-69d2d',
    authDomain: 'cipher-affair-69d2d.firebaseapp.com',
    storageBucket: 'cipher-affair-69d2d.appspot.com',
    measurementId: 'G-QPCQ2ZRMSS',
  );
}
